version: 2
root-markers:
  - .envrc
  - .git/
format-debounce: 1s
lint-debounce: 1s

tools:
  python-mypy: &python-mypy
    prefix: mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

languages:
  python:
    - <<: *python-mypy
