#!/usr/bin/env python

import os
import sys
from pathlib import Path
from subprocess import run


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: mkdir <directory>")  # noqa: T201
        return 1

    directory = sys.argv[1]
    path = Path(directory).absolute()
    path.mkdir(exist_ok=True, parents=True)

    lf_id = os.environ["id"]
    escaped_path = str(path).replace('"', '\\"')
    send_command = f'send {lf_id} select "{escaped_path}"'
    run(["lf", "-remote", send_command], check=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
