return {
    "romus204/tree-sitter-manager.nvim",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "css",
            "dockerfile",
            "gitcommit",
            "gitignore",
            "go",
            "gotmpl",
            "helm",
            "html",
            "javascript",
            "json",
            "lua",
            "make",
            "markdown",
            "python",
            "rust",
            "toml",
            "typescript",
            "vim",
            "vimdoc",
            "yaml",
        },
        auto_install = true,
        highlight = true,
        border = "single",
    },
}
