name = "chezmoi"
directory = "~/.local/share/chezmoi"

[[windows]]
name = "editor"

[[windows.panes]]
focus = true
command = "nvim"

[[windows]]
name = "shell"

[[windows]]
name = "git"

[[windows.panes]]
command = "lazygit"
